name: Build libvips

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: macos
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libglib2.0-dev \
          libexpat1-dev \
          ninja-build \
          meson \
          libjpeg-dev \
          libpng-dev \
          libtiff5-dev \
          libwebp-dev \
          libexif-dev \
          librsvg2-dev \
          libraw-dev \
          liblcms2-dev \
          libfftw3-dev \
          liborc-0.4-dev \
          libarchive-dev \
          libmatio-dev \
          libcfitsio-dev \
          libnifti-dev \
          libheif-dev \
          libjxl-dev \
          libopenjp2-7-dev \
          libopenexr-dev \
          libpango1.0-dev \
          libcairo2-dev \
          libpoppler-glib-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install \
          meson \
          ninja \
          pkg-config \
          glib \
          expat \
          jpeg \
          libpng \
          libtiff \
          webp \
          libexif \
          librsvg \
          libraw \
          little-cms2 \
          fftw \
          orc \
          libarchive \
          libmatio \
          cfitsio \
          libheif \
          jpeg-xl \
          openjpeg \
          openexr \
          pango \
          cairo \
          poppler

    - name: Prepare macOS environment
      if: runner.os == 'macOS'
      run: |
        echo "PKG_CONFIG_PATH=$(brew --prefix mozjpeg)/lib/pkgconfig:$(brew --prefix libarchive)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Setup build directory
      run: |
        cd libvips
        meson setup build \
            --buildtype=release \
            -Ddebug=false \
            -Ddeprecated=false \
            -Dmagick=disabled \
            -Ddocs=false

    - name: Compile libvips
      run: |
        cd libvips
        meson compile -C build

    - name: Run tests
      run: |
        cd libvips/build
        meson test

    - name: Install libvips
      run: |
        cd libvips/build
        meson install --destdir=../install

    - name: Tar and Gzip
      run: tar -czvf libvips-${{ matrix.name }}.tar.gz libvips/install/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libvips-${{ matrix.name }}.tar.gz
        path: libvips-${{ matrix.name }}.tar.gz
