name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true
    - run: find .
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          libvips-linux.tar.gz
          libvips-macos.tar.gz
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: false
